### ISSUE TITLE
"survey" vs "surveys" in views folder path

### ISSUE THREAD

**Issue by TaiwoAyanleye** [createdbypete/createdbypete.github.io#20]
Hey Pete,

Shouldn't this be "surveys" folder? Wondering because you have it as "survey" folder on your blog post.

"app/views/survey/answers.html.erb"

**Comment by createdbypete** [comment]
Yes it should be, good spot. Thanks :+1:

**Comment by Salomanuel** [comment]
Oh, thanks goodness, I was getting crazy!   
The typo is still there, please fix it   
    `# app/views/survey/answers.html.erb`
    `<h1><%= @survey.name %> Answers</h1>`

http://www.createdbypete.com/articles/working-with-nested-forms-and-a-many-to-many-association-in-rails-4/

**Comment by createdbypete** [comment]
Hey @Salomanuel thanks for bringing this up again. I've just fixed the typo sorry 🙈
