### ISSUE TITLE
Rsync guide is great, but for one part

### ISSUE THREAD

**Issue by damnsalvation** [createdbypete/createdbypete.github.io#21]
This part: $(date +'%Y-%m-%d') doesn't expand properly if it's in crontab.
Works great if you just escape everything:  $(date +\%Y\-\%m\-\%d)

Still, your guide told me almost everything I wanted to know, I just needed to figure out how to get the variables to expand.

**Comment by createdbypete** [comment]
@damnsalvation thanks for pointing that out, I'll update the post!

**Comment by damnsalvation** [comment]
Cool!
I just discovered that most of my servers choked on the whitespace around
the + as well.  So it should be date+\%Y, not date + \%Y.  Apparently some
old releases don't choke on it, like the one I tested it on.

**Comment by createdbypete** [comment]
I found `echo $(date +\%Y-\%m-\%d)` works but `echo $(date+\%Y-\%m-\%d)` doesn't work: 
```
zsh: command not found: date+%Y-%m-%d
```

**Comment by damnsalvation** [comment]
Yup, my mistake.  The space *after* the + was the problem, the one in front
is necessary.  Boneheaded mistake on my part.

**Comment by createdbypete** [comment]
Haha no worries, we are always learning :smile:
