### ISSUE TITLE
Question about an rsync destination

### ISSUE THREAD

**Issue by boneshark1** [createdbypete/createdbypete.github.io#24]
First thanks for the helpful guide on rsync

I have setup a sync that works pretty much.  The one item that is irritating is that I have a structure in the source that includes a recursive mountpoint such as (some directories excluded:
/mnt/NAS_5TB
  NAS_5TB/Acronis​
  NAS_5TB/Music (**this has all the media files)​**
  NAS_5TB/iocage​
    NAS_5TB/iocage/jails​
      NAS_5TB/iocage/jails/plex​
         NAS_5TB/iocage/jails/plex/root​
            NAS_5TB/iocage/jails/plex/root /media​
               NAS_5TB/iocage/jails/plex/root/media/**mountpoint back to NAS_5TB/Music**
So when my rsync runs it copies not only the media directory but also copies (redundantly) all the media files again because of the mountpoint.  I can put an exclude in the rsync command line but my question is:  If I manually delete the redundant files from the rsync destination will it invalidate the destination?  In other words will manually modifying the data in the rsync destination affect the integrity of the destination structure?

**Comment by createdbypete** [comment]
Hey, sorry for the delay think I turned off email notifications. To your issue though… if you've excluded that directory then you should be fine to clear up the destination as you see fit and it will not try and copy things later. You can always use the `--dry-run` option with `--verbose` to see what files it would pick up as changed. I often do this just to see what would happen/see if I want to exclude any files without having to wait for the data transfer.

Hope that helps.

**Comment by boneshark1** [comment]
Thanks for the note this was what. I was looking for

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
